config/routes.rb
Rails.application.routes.draw do
  root  'static_pages#home'
  get   '/about',   to: 'static_pages#about'
  get   '/contact', to: 'static_pages#contact'
  get   '/signup',  to: 'users#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_landing_page.html.erb
                             <!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="brand-heading">Welcome to Tim's Corner</h1>
                        <% flash.each do |message_type, message| %>
                            <div class="alert alert-<%= message_type %>"><%= message %></div>
                        <% end %>
                        <p class="intro-text">A Twitter Clone Application Built with the Ruby on Rails Framework.</p>
                        <%= link_to "Log In", login_path, class: "btn btn-default btn-lg" %>
                        <%= link_to "Sign Up", signup_path, class: "btn btn-default btn-lg" %>
                    </div>
                </div>
            </div>
        </div>
    </header>
  </body>
</html>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, html: { multipart: true }) do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose a new micropost . . ." %>
  </div>
  <%= f.submit "Post", class: "btn btn-default btn-lg" %>
  <span class="picture">
    <%= f.file_field :picture, accept: "image/jpeg,image/gif,image/png,image/ico" %>
  </span>
<% end %>

<script type="text/javascript">
  $("#micropost_picture").bind("change", function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert("Maximum file size is 5MB. Please choose a smaller file.");
    }
  });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats text-center">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    Following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    Followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<h1 class="text-center">
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<%= current_user.name %>
</h1>
<span><%= link_to "View My Profile", current_user %></span><BR>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/shared/_user_posts.html.erb
<section id="micropost_form" class="container content-section">
  <div class="row">
    <aside class="col-md-6 col-md-offset-3">
      <% flash.each do |message_type, message| %>
                    <div class="alert alert-<%= message_type %>"><%= message %></div>
                <% end %>
      <section class="user_info text-center">
        <%= render "shared/user_info" %>
      </section>
      <section class="micropost_form">
        <%= render "shared/micropost_form" %>
      </section>
      <section class="micropost feed text-center">
        <h3>Micropost Feed</h3>
        <%= render "shared/feed" %>
      </section>
    </aside>