config/routes.rb
Rails.application.routes.draw do
  root  'static_pages#home'
  get   '/about',   to: 'static_pages#about'
  get   '/contact', to: 'static_pages#contact'
  get   '/signup',  to: 'users#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
    <!-- Footer -->
    <footer>
      <nav class="text-center">
          <ul>
            <li>
              <li><%= link_to "About Me",    about_path %> |</li>
            </li>
              <li>
                <li><%= link_to "Contact",    contact_path %></li>
              </li>
            </ul>
      </nav>
        <div class="container text-center">
            <p>Copyright &copy; Tim's Corner 2016</p>
        </div>
    </footer>

app/views/layouts/_head.html.erb
<%= csrf_meta_tags %>
    <%= stylesheet_link_tag      'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag      'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>

app/views/layouts/_header.html.erb
    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="/">
                    <i class="fa fa-play-circle"></i> <span class="light">Tim's</span> Corner
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                     <li>
                        <li><%= link_to "Home",    root_path %></li>
                    </li>
                    <li>
                    </li>
                    <% if logged_in? %>
                        <li><%= link_to "Users", users_path %></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Account <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                              <li><%= link_to "Profile", current_user %></li>
                              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                              <li class="divider"></li>
                              <li>
                                <%= link_to "Log out", logout_path, method: "delete" %>
                              </li>
                            </ul>
                          </li>
                        <% else %>
                          <li><%= link_to "Log in", login_path %></li>
                        <% end %>
                      </ul>
                    </div>
            <!-- /.navbar-collapse -->
                </div>
        <!-- /.container -->
    </nav>

app/views/layouts/_shim.html.erb
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<html lang="en">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/head' %>
    <%= render 'layouts/shim' %>
  </head>
  <body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <%= render 'layouts/header' %>
    <%= yield %>

    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>